import type { Metadata } from "next";
import { Rubik, Zain } from "next/font/google";
import "../globals.css";
import { hasLocale, NextIntlClientProvider } from "next-intl";
import { getDirection } from "@/i18n/getDirection";
import { notFound } from "next/navigation";
import { routing } from "@/i18n/routing";
import Navbar from "@/components/navbar/Navbar";
import { Toaster } from "sonner";

export const rubik = Rubik({
  subsets: ["arabic", "latin"],
  variable: "--font-rubik",
});

export const zain = Zain({
  subsets: ["arabic", "latin"],
  weight: ["300", "400", "700", "800", "900"],
  variable: "--font-zain",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  params,
  children,
}: Readonly<{
  params: Promise<{ locale: string }>;
  children: React.ReactNode;
}>) {
  // Ensure that the incoming `locale` is valid
  const { locale } = await params;
  const dir = getDirection(locale);

  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }

  return (
    <html
      lang={locale}
      dir={dir}
      className={`${rubik.variable} ${zain.variable} h-full antialiased`}
    >
      <body className="min-h-screen overflow-x-hidden relative flex flex-col">
        <NextIntlClientProvider>
          <Toaster richColors position="top-right" />
          <Navbar />
          {children}
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
